/* ==============================================================
   Suren-Daten — 1:1 aus der "Elif & Ba"-App übernommen (05.08.2026,
   Nachtausbau Punkt 1). Arabischer Text: quran-simple (alquran.cloud),
   Übersetzung: Bubenheim & Elyas, Umschrift: türkische Kurs-Lesart,
   kindgerechte Bedeutungen + "Wusstest du?". audioStart = globale
   Ayah-Nummer für die Alafasy-Rezitation (cdn.islamic.network).
   ============================================================== */
window.SURAH_BASMALA = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ";
window.SURAH_BASMALA_TR = "Bismillâhir-rahmânir-rahîm";
window.SURAH_BASMALA_DE = "Im Namen Allahs, des Allerbarmers, des Barmherzigen.";
window.SURAHS_DATA = [
 {n:1, name:"Al-Fatiha", arName:"الفاتحة", deName:"Die Eröffnende", place:"Mekka", basmala:false, audioStart:1,
  meaning:"Diese Sure ist wie ein Gespräch mit Allah. Wir loben ihn, danken ihm und bitten ihn: „Zeig uns den richtigen, geraden Weg!“ Muslime sprechen diese Sure in jedem Gebet – sie ist das Herz des Gebets.",
  fact:"Al-Fatiha heißt „die Eröffnende“, weil sie den Koran eröffnet. In den fünf täglichen Gebeten sprechen wir sie mindestens 17-mal am Tag!",
  ayahs:[
   {ar:"بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", tr:"Bismillâhir-rahmânir-rahîm", de:"Im Namen Allahs, des Allerbarmers, des Barmherzigen."},
   {ar:"الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", tr:"Elhamdü lillâhi rabbil-âlemîn", de:"(Alles) Lob gehört Allah, dem Herrn der Welten,"},
   {ar:"الرَّحْمَٰنِ الرَّحِيمِ", tr:"Er-rahmânir-rahîm", de:"dem Allerbarmer, dem Barmherzigen,"},
   {ar:"مَالِكِ يَوْمِ الدِّينِ", tr:"Mâliki yevmid-dîn", de:"dem Herrscher am Tag des Gerichts."},
   {ar:"إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", tr:"İyyâke na'büdü ve iyyâke neste'în", de:"Dir allein dienen wir, und zu Dir allein flehen wir um Hilfe."},
   {ar:"اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", tr:"İhdinas-sırâtal-müstekîm", de:"Leite uns den geraden Weg,"},
   {ar:"صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", tr:"Sırâtallezîne en'amte aleyhim, ğayril-mağdûbi aleyhim ve led-dâllîn", de:"den Weg derjenigen, denen Du Gunst erwiesen hast, nicht derjenigen, die (Deinen) Zorn erregt haben, und nicht der Irregehenden!"},
  ]},
 {n:103, name:"Al-Asr", arName:"العصر", deName:"Die Zeit", place:"Mekka", basmala:true, audioStart:6177,
  meaning:"Allah schwört bei der Zeit: Sie rennt schnell davon! Menschen verlieren, wenn sie ihre Zeit verschwenden. Gewinner sind die, die glauben, Gutes tun, ehrlich sind und geduldig bleiben – und einander dabei helfen.",
  fact:"Der große Gelehrte Imam Schafi'i sagte: Wenn die Menschen nur über diese kurze Sure richtig nachdenken würden, würde sie ihnen als Wegweiser genügen.",
  ayahs:[
   {ar:"وَالْعَصْرِ", tr:"Vel-asr", de:"Beim Zeitalter!"},
   {ar:"إِنَّ الْإِنْسَانَ لَفِي خُسْرٍ", tr:"İnnel-insâne lefî husr", de:"Der Mensch befindet sich wahrlich in Verlust,"},
   {ar:"إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ", tr:"İllellezîne âmenû ve amilus-sâlihâti ve tevâsav bil-hakkı ve tevâsav bis-sabr", de:"außer denjenigen, die glauben und rechtschaffene Werke tun und einander die Wahrheit eindringlich empfehlen und einander die Standhaftigkeit eindringlich empfehlen."},
  ]},
 {n:105, name:"Al-Fil", arName:"الفيل", deName:"Der Elefant", place:"Mekka", basmala:true, audioStart:6189,
  meaning:"Vor langer Zeit wollte ein König namens Abraha mit einer riesigen Armee und Elefanten die Kaaba zerstören. Aber Allah beschützte sein Haus: Er schickte Schwärme kleiner Vögel mit Steinchen, und die mächtige Armee wurde besiegt. Niemand ist stärker als Allah!",
  fact:"Das geschah in dem Jahr, in dem der Prophet Muhammad ﷺ geboren wurde. Man nennt es bis heute das „Jahr des Elefanten“.",
  ayahs:[
   {ar:"أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ", tr:"E lem tera keyfe feale rabbüke bi-ashâbil-fîl", de:"Siehst du nicht, wie dein Herr mit den Leuten des Elefanten verfuhr?"},
   {ar:"أَلَمْ يَجْعَلْ كَيْدَهُمْ فِي تَضْلِيلٍ", tr:"E lem yec'al keydehüm fî tadlîl", de:"Ließ Er nicht ihre List verlorengehen"},
   {ar:"وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ", tr:"Ve ersele aleyhim tayran ebâbîl", de:"und sandte gegen sie Vögel in aufeinanderfolgenden Schwärmen,"},
   {ar:"تَرْمِيهِمْ بِحِجَارَةٍ مِنْ سِجِّيلٍ", tr:"Termîhim bi-hıcâratin min siccîl", de:"die sie mit Steinen aus gebranntem Lehm bewarfen,"},
   {ar:"فَجَعَلَهُمْ كَعَصْفٍ مَأْكُولٍ", tr:"Fe-cealehüm ke-asfin me'kûl", de:"und sie so wie abgefressene Halme machte?"},
  ]},
 {n:106, name:"Quraisch", arName:"قريش", deName:"Die Quraisch", place:"Mekka", basmala:true, audioStart:6194,
  meaning:"Der Stamm der Quraisch lebte in Mekka. Allah schenkte ihnen sichere Handelsreisen im Winter und im Sommer, genug Essen und Sicherheit. Dafür sollten sie dankbar sein und nur Allah dienen – dem Herrn der Kaaba.",
  fact:"Die Quraisch waren der Stamm des Propheten Muhammad ﷺ. Ihre Karawanen reisten im Winter in den Jemen und im Sommer nach Syrien.",
  ayahs:[
   {ar:"لِإِيلَافِ قُرَيْشٍ", tr:"Li-îlâfi Kurayş", de:"Für die Vereinigung der Quraiš,"},
   {ar:"إِيلَافِهِمْ رِحْلَةَ الشِّتَاءِ وَالصَّيْفِ", tr:"Îlâfihim rıhleteş-şitâi ves-sayf", de:"ihre Vereinigung während der Reise des Winters und des Sommers."},
   {ar:"فَلْيَعْبُدُوا رَبَّ هَٰذَا الْبَيْتِ", tr:"Fel-ya'büdû rabbe hâzel-beyt", de:"So sollen sie dem Herrn dieses Hauses dienen,"},
   {ar:"الَّذِي أَطْعَمَهُمْ مِنْ جُوعٍ وَآمَنَهُمْ مِنْ خَوْفٍ", tr:"Ellezî at'amehüm min cûin ve âmenehüm min havf", de:"Der ihnen Speise nach ihrem Hunger gegeben und ihnen Sicherheit nach ihrer Furcht gewährt hat."},
  ]},
 {n:107, name:"Al-Ma'un", arName:"الماعون", deName:"Die Hilfeleistung", place:"Mekka", basmala:true, audioStart:6198,
  meaning:"Diese Sure zeigt: Glauben erkennt man an guten Taten. Wer Waisenkinder wegstößt und Armen nicht hilft, hat den Glauben nicht verstanden. Und wer nur betet, damit andere ihn sehen, macht es falsch. Sei hilfsbereit – auch mit kleinen Dingen!",
  fact:"„Al-Ma'un“ bedeutet kleine Alltagshilfen – zum Beispiel dem Nachbarn etwas ausleihen. Sogar solche kleinen Dinge sind im Islam wichtig!",
  ayahs:[
   {ar:"أَرَأَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ", tr:"E raeytellezî yükezzibü bid-dîn", de:"Siehst du (nicht) denjenigen, der das Gericht für Lüge erklärt?"},
   {ar:"فَذَٰلِكَ الَّذِي يَدُعُّ الْيَتِيمَ", tr:"Fe-zâlikellezî yedu''ul-yetîm", de:"Das ist derjenige, der die Waise zurückstößt"},
   {ar:"وَلَا يَحُضُّ عَلَىٰ طَعَامِ الْمِسْكِينِ", tr:"Ve lâ yehuddu alâ taâmil-miskîn", de:"und nicht zur Speisung des Armen anhält."},
   {ar:"فَوَيْلٌ لِلْمُصَلِّينَ", tr:"Fe-veylün lil-musallîn", de:"Wehe nun den Betenden,"},
   {ar:"الَّذِينَ هُمْ عَنْ صَلَاتِهِمْ سَاهُونَ", tr:"Ellezîne hüm an salâtihim sâhûn", de:"denjenigen, die auf ihre Gebete nicht achten,"},
   {ar:"الَّذِينَ هُمْ يُرَاءُونَ", tr:"Ellezîne hüm yürâûn", de:"denjenigen, die dabei (nur) gesehen werden wollen;"},
   {ar:"وَيَمْنَعُونَ الْمَاعُونَ", tr:"Ve yemneûnel-mâûn", de:"und die Hilfeleistung verweigern!"},
  ]},
 {n:108, name:"Al-Kauthar", arName:"الكوثر", deName:"Die Fülle", place:"Mekka", basmala:true, audioStart:6205,
  meaning:"Allah tröstet den Propheten ﷺ: „Wir haben dir al-Kauthar geschenkt“ – einen wunderschönen Fluss im Paradies und ganz viel Gutes. Darum: Bete zu Allah und sei dankbar! Wer den Propheten hasst, verliert am Ende selbst.",
  fact:"Al-Kauthar ist die kürzeste Sure im ganzen Koran – nur 3 Verse! Und sie erzählt von einem Fluss im Paradies.",
  ayahs:[
   {ar:"إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ", tr:"İnnâ a'taynâkel-kevser", de:"Wir haben dir ja al-Kautar gegeben."},
   {ar:"فَصَلِّ لِرَبِّكَ وَانْحَرْ", tr:"Fe-salli li-rabbike venhar", de:"So bete zu deinem Herrn und opfere."},
   {ar:"إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ", tr:"İnne şânieke hüvel-ebter", de:"Gewiß, derjenige, der dich haßt, – er ist vom Guten abgetrennt."},
  ]},
 {n:109, name:"Al-Kafirun", arName:"الكافرون", deName:"Die Ungläubigen", place:"Mekka", basmala:true, audioStart:6208,
  meaning:"Einige Leute in Mekka schlugen dem Propheten ﷺ einen Tausch vor: „Bete unsere Götter an, dann beten wir deinen Gott an.“ Die Antwort war klar: Nein! Wir beten nur Allah an. „Ihr habt eure Religion, und ich habe meine.“ Beim Glauben an Allah gibt es keine faulen Kompromisse – aber auch keinen Zwang.",
  fact:"Der Prophet ﷺ rezitierte diese Sure gerne – zum Beispiel vor dem Schlafengehen.",
  ayahs:[
   {ar:"قُلْ يَا أَيُّهَا الْكَافِرُونَ", tr:"Kul yâ eyyühel-kâfirûn", de:"Sag: O ihr Ungläubigen,"},
   {ar:"لَا أَعْبُدُ مَا تَعْبُدُونَ", tr:"Lâ a'büdü mâ ta'büdûn", de:"ich diene nicht dem, dem ihr dient,"},
   {ar:"وَلَا أَنْتُمْ عَابِدُونَ مَا أَعْبُدُ", tr:"Ve lâ entüm âbidûne mâ a'büd", de:"und ihr dient nicht Dem, Dem ich diene."},
   {ar:"وَلَا أَنَا عَابِدٌ مَا عَبَدْتُمْ", tr:"Ve lâ ene âbidün mâ abedtüm", de:"Und ich werde (auch) nicht dem dienen, dem ihr gedient habt,"},
   {ar:"وَلَا أَنْتُمْ عَابِدُونَ مَا أَعْبُدُ", tr:"Ve lâ entüm âbidûne mâ a'büd", de:"und ihr werdet nicht Dem dienen, Dem ich diene."},
   {ar:"لَكُمْ دِينُكُمْ وَلِيَ دِينِ", tr:"Leküm dînüküm ve liye dîn", de:"Euch eure Religion und mir meine Religion."},
  ]},
 {n:110, name:"An-Nasr", arName:"النصر", deName:"Die Hilfe", place:"Medina", basmala:true, audioStart:6214,
  meaning:"Als Allahs Hilfe kam, konnten die Muslime friedlich nach Mekka zurückkehren, und sehr viele Menschen nahmen den Islam an. Die Sure lehrt: Wenn du Erfolg hast, gib nicht an – danke Allah und bitte ihn um Vergebung.",
  fact:"Dies war eine der letzten Suren, die dem Propheten ﷺ offenbart wurden.",
  ayahs:[
   {ar:"إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ", tr:"İzâ câe nasrullâhi vel-feth", de:"Wenn Allahs Hilfe kommt und der Sieg"},
   {ar:"وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا", tr:"Ve raeyten-nâse yedhulûne fî dînillâhi efvâcâ", de:"und du die Menschen in Allahs Religion in Scharen eintreten siehst,"},
   {ar:"فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ إِنَّهُ كَانَ تَوَّابًا", tr:"Fe-sebbih bi-hamdi rabbike vestağfirh, innehû kâne tevvâbâ", de:"dann lobpreise deinen Herrn und bitte Ihn um Vergebung; gewiß, Er ist Reueannehmend."},
  ]},
 {n:111, name:"Al-Masad", arName:"المسد", deName:"Die Palmfasern", place:"Mekka", basmala:true, audioStart:6217,
  meaning:"Abu Lahab war ein Onkel des Propheten ﷺ, aber er war sehr gemein zu ihm und bekämpfte den Islam. Auch seine Frau machte mit und legte dem Propheten Dornen in den Weg. Die Sure warnt: Reichtum und Angeberei helfen nicht, wenn man böse handelt.",
  fact:"„Abu Lahab“ war ein Spitzname und bedeutet „Vater der Flamme“ – man sagt, sein Gesicht leuchtete rötlich.",
  ayahs:[
   {ar:"تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ", tr:"Tebbet yedâ ebî lehebin ve tebb", de:"Zugrunde gehen sollen die Hände Abu Lahabs, und zugrunde gehen soll er (selbst)!"},
   {ar:"مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ", tr:"Mâ ağnâ anhü mâlühû ve mâ keseb", de:"Was nützt ihm sein Besitz und das, was er erworben hat?"},
   {ar:"سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ", tr:"Se-yaslâ nâran zâte leheb", de:"Er wird einem Feuer voller Flammen ausgesetzt sein"},
   {ar:"وَامْرَأَتُهُ حَمَّالَةَ الْحَطَبِ", tr:"Vemraetühû hammâletel-hatab", de:"und (auch) seine Frau, die Brennholzträgerin."},
   {ar:"فِي جِيدِهَا حَبْلٌ مِنْ مَسَدٍ", tr:"Fî cîdihâ hablün min mesed", de:"Um ihrem Hals ist ein Strick aus Palmfasern."},
  ]},
 {n:112, name:"Al-Ichlas", arName:"الإخلاص", deName:"Die Aufrichtigkeit", place:"Mekka", basmala:true, audioStart:6222,
  meaning:"Diese kleine Sure erklärt das Allerwichtigste über Allah: Er ist Einer. Er braucht nichts und niemanden – aber alle brauchen ihn. Er hat keine Kinder und keine Eltern, und nichts und niemand ist wie er.",
  fact:"Der Prophet ﷺ sagte: Diese Sure ist so wertvoll wie ein Drittel des Korans!",
  ayahs:[
   {ar:"قُلْ هُوَ اللَّهُ أَحَدٌ", tr:"Kul hüvellâhü ehad", de:"Sag: Er ist Allah, ein Einer,"},
   {ar:"اللَّهُ الصَّمَدُ", tr:"Allâhüs-samed", de:"Allah, der Überlegene."},
   {ar:"لَمْ يَلِدْ وَلَمْ يُولَدْ", tr:"Lem yelid ve lem yûled", de:"Er hat nicht gezeugt und ist nicht gezeugt worden,"},
   {ar:"وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ", tr:"Ve lem yekün lehû küfüven ehad", de:"und niemand ist Ihm jemals gleich."},
  ]},
 {n:113, name:"Al-Falaq", arName:"الفلق", deName:"Das Morgengrauen", place:"Mekka", basmala:true, audioStart:6226,
  meaning:"Mit dieser Sure bitten wir Allah um Schutz – vor allem Bösen, vor der dunklen Nacht, vor Zauberei und vor neidischen Menschen. Allah, der Herr des Morgenlichts, passt auf uns auf.",
  fact:"Al-Falaq und An-Nas heißen zusammen „die beiden Schutzsuren“. Der Prophet ﷺ las sie abends, pustete sanft in seine Hände und strich damit über sich.",
  ayahs:[
   {ar:"قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", tr:"Kul eûzü bi-rabbil-felak", de:"Sag: Ich nehme Zuflucht beim Herrn des Tagesanbruchs"},
   {ar:"مِنْ شَرِّ مَا خَلَقَ", tr:"Min şerri mâ halak", de:"vor dem Übel dessen, was Er erschaffen hat,"},
   {ar:"وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ", tr:"Ve min şerri ğâsikın izâ vekab", de:"und vor dem Übel der Dunkelheit, wenn sie zunimmt,"},
   {ar:"وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ", tr:"Ve min şerrin-neffâsâti fil-ukad", de:"und vor dem Übel der Knotenanbläserinnen"},
   {ar:"وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ", tr:"Ve min şerri hâsidin izâ hased", de:"und vor dem Übel eines (jeden) Neidenden, wenn er neidet."},
  ]},
 {n:114, name:"An-Nas", arName:"الناس", deName:"Die Menschen", place:"Mekka", basmala:true, audioStart:6231,
  meaning:"Auch diese Sure ist wie ein Schutzschild: Wir bitten Allah, den Herrn und König aller Menschen, um Schutz vor dem Einflüsterer, der uns heimlich zu schlechten Gedanken verführen will. Wenn du Angst hast – lies diese Sure!",
  fact:"An-Nas ist die allerletzte Sure im Koran. Das Wort „Menschen“ (an-nās) kommt in ihren 6 Versen gleich fünfmal vor.",
  ayahs:[
   {ar:"قُلْ أَعُوذُ بِرَبِّ النَّاسِ", tr:"Kul eûzü bi-rabbin-nâs", de:"Sag: Ich nehme Zuflucht beim Herrn der Menschen,"},
   {ar:"مَلِكِ النَّاسِ", tr:"Melikin-nâs", de:"dem König der Menschen,"},
   {ar:"إِلَٰهِ النَّاسِ", tr:"İlâhin-nâs", de:"dem Gott der Menschen,"},
   {ar:"مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ", tr:"Min şerril-vesvâsil-hannâs", de:"vor dem Übel des Einflüsterers, des Davonschleichers,"},
   {ar:"الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ", tr:"Ellezî yüvesvisü fî sudûrin-nâs", de:"der in die Brüste der Menschen einflüstert,"},
   {ar:"مِنَ الْجِنَّةِ وَالنَّاسِ", tr:"Minel-cinneti ven-nâs", de:"von den Ginn und den Menschen."},
  ]},
];
